### ISSUE TITLE
Dashboard view

### ISSUE THREAD

**Issue by jasonmadigan** [Kuadrant/console-plugin#20]
Build a high-level dashboard view for the plugin:

- Lists policies, with a project/NS selector
- Surfaces "high-level/critical" alerts if available (with deep links to elsewhere)
- Maybe: surface missing dependencies (e.g. `cert-manager`, Istio)

**Comment by david-martin** [comment]
> * Surfaces "high-level/critical" alerts if available (with deep links to elsewhere)

We may be able to leverage the ocp api for alerts that the console uses e.g. /api/prometheus/api/v1/rules

> deep links to elsewhere

Could link directly to the Observe > Alerts view at  `/monitoring/alerts?rowFilter-alert-state=firing&rowFilter-alert-source=user`, filtered to user alerts rather than platform alerts

**Comment by jasonmadigan** [comment]
superseded by #33 33
