### ISSUE TITLE
Create gateway picker

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/console-plugin#32]
### WHAT:
 Create a gateway picker component for policy forms to allow for less values to be filled out by the user for gateways.

**Comment by jasonmadigan** [comment]
Don't think we need a specific view for this after all:

https://github.com/Kuadrant/console-plugin/blob/4e60d8356726f261807e7f8e7523edd53a8affc1/src/components/KuadrantDNSPolicyCreatePage.tsx#L110-L127
