### ISSUE TITLE
Create the Overview / Dashboard view

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/console-plugin#33]
### WHAT: 
Create the "overview" / dashboard view of the policies 

In the Developer perspective, users should be able to list: AuthPolicy, RateLimitPolicy
In the Administrator perspective, users should be able to list all types of policy
HTTP view ???
Alerts can be seen by both perspectives 

Mockup: https://www.figma.com/proto/r6rh1Jkx9vI9G2pXv0rT2D/OCP-Dynamic-plugin-(GA)?node-id=12-4426&starting-point-node-id=25%3A9737&t=kv38KEsG4khvHPIj-1

Build a high-level dashboard view for the plugin:

- Lists policies, with a project/NS selector
- Surfaces "high-level/critical" alerts if available (with deep links to elsewhere)
- Maybe: surface missing dependencies (e.g. `cert-manager`, Istio)

**Comment by jasonmadigan** [comment]
Build a high-level dashboard view for the plugin:

Lists policies, with a project/NS selector
Surfaces "high-level/critical" alerts if available (with deep links to elsewhere)
Maybe: surface missing dependencies (e.g. cert-manager, Istio)
