### ISSUE TITLE
Create/update auth policy

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/console-plugin#34]
WHAT:
Support for creating and updating Kuadrant policies (auth) via the UI, yaml view.

HOW:

For updating we should follow the same syntax off not being able to save the yaml if a field is changed that's not allowed to be changed

Mockup discussed with UI are what we want the end goal to look like.
Call recording: https://drive.google.com/file/d/1YG_nmMuB6hgvL-bnciKgvbdjO3DBhcaF/view?usp=drive_web
Mockup: https://www.figma.com/proto/r6rh1Jkx9vI9G2pXv0rT2D/OCP-Dynamic-plugin-(GA)?page-id=0%3A1&node-id=42-5365&viewport=1101%2C329%2C0.39&t=1Z0YW11ZmJEPrOJX-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=21%3A8212

**Comment by jasonmadigan** [comment]
👀
